binance_p2p_converter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('converter.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

converter/urls.py
from django.urls import path

from . import views

app_name = 'converter'

urlpatterns = [
    path('payment_methods/',
         views.get_payment_methods,
         name='payment_methods'),
    path('get_offers/',
         views.get_offers,
         name='get_offers'),
    path('', views.index, name='index'),
]

converter_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('converter.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

converter/forms.py
"""Currency converter forms."""
import logging

from django import forms
from django.core.exceptions import ValidationError
from dynamic_forms import DynamicField, DynamicFormMixin

from .models import Currency, PaymentMethod

logger = logging.getLogger(__name__)


class ConverterForm(DynamicFormMixin, forms.Form):
    """Currency converter form."""

    from_currency = forms.ModelChoiceField(
        queryset=Currency.objects.all()
    )
    to_currency = forms.ModelChoiceField(
        queryset=Currency.objects.all()
    )
    from_payment_methods = DynamicField(
        forms.ModelChoiceField,
        queryset=lambda form: PaymentMethod.objects.filter(
            currency=form['from_currency'].value()),
        initial=lambda form: PaymentMethod.objects.filter(
            currency=form['from_currency'].value()).first(),
    )
    to_payment_methods = DynamicField(
        forms.ModelChoiceField,
        queryset=lambda form: PaymentMethod.objects.filter(
            currency=form['to_currency'].value()),
        initial=lambda form: PaymentMethod.objects.filter(
            currency=form['to_currency'].value()).first(),
    )
    from_amount = forms.FloatField(required=False)
    to_amount = forms.FloatField(required=False)

    is_merchant = forms.BooleanField(required=False, initial=True)

    def clean(self):
        cleaned_data = super().clean()
        from_amount = cleaned_data.get('from_amount')
        to_amount = cleaned_data.get('to_amount')
        from_currency = cleaned_data.get('from_currency')
        to_currency = cleaned_data.get('to_currency')

        if not from_amount and not to_amount:
            raise ValidationError('Please fill one of amount fields!')

        if from_amount and to_amount:
            raise ValidationError('Please fill only one amount field!')

        if from_currency == to_currency:
            raise ValidationError('From and to currencies cannot be the same!')

        if from_amount and from_amount <= 0 or to_amount and to_amount <= 0:
            raise ValidationError('Amount should be greater than zero!')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Binance p2p currency converter</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous">
  </head>
  <body>
    <div class="container mt-2">
      {% include 'converter/includes/messages.html' %}
      {% block content %}
      {% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
    <script>
      $(document).ready(function() {
         $("#id_from_amount").keydown(function(){
             $("#id_to_amount").val("");
         })
         $("#id_to_amount").keydown(function(){
             $("#id_from_amount").val("");
         })
         setTimeout(function() {
          $('.alert').fadeOut("slow");
      }, 10000);
      });
    </script>
  </body>
</html>